version: '3.1'
services:
    angular:
        build:
            context: ./
            dockerfile: AngularDocker
        volumes:
            - ./app/:/usr/local/app/
        ports:
            - 3000:80
    flask:
        build:
            context: ./
            dockerfile: FlaskDocker
        volumes:
            - ./api/:/api
        ports:
          - 5000:5000